<a href="https://colab.research.google.com/github/Joshi-Atharva/Sentiment-analysis/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# Mounting the drive to use the files and images
import os
os.chdir('/content/drive/MyDrive/Sentiment analysis/')
print(os.listdir())
from extract_bin import extract_bin, split

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['Sentiment analysis.ipynb', 'train_set_sentiment.txt', 'extract.py', '__pycache__', 'train_set.txt', 'trainDataSet.txt', 'amazon_cells_labelled.txt', 'extract_bin.py']


In [2]:
file_path = 'amazon_cells_labelled.txt'
data = extract_bin(file_path)
inputs = data.inputs
labels = data.labels
split_object = split(inputs, labels, 700)
train_inputs = split_object.train_set_inputs
train_labels = split_object.train_set_labels
test_inputs = split_object.test_set_inputs
test_labels = split_object.test_set_labels
print(train_inputs)
print(train_labels)

['So there is no way for me to plug it in here in the US unless I go by a converter.\t', 'Good case, Excellent value.\t', 'Great for the jawbone.\t', 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!\t', 'The mic is great.\t', 'I have to jiggle the plug to get it to line up right to get decent volume.\t', 'If you have several dozen or several hundred contacts, then imagine the fun of sending each of them one by one.\t', 'If you are Razr owner...you must have this!\t', 'Needless to say, I wasted my money.\t', 'What a waste of money and time!.\t', 'And the sound quality is great.\t', 'He was very impressed when going from the original battery to the extended battery.\t', 'If the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound from the headset.\t', 'Very good quality though\t', 'The design is very odd, as the ear "clip" is not very comfortable at all.\t', 'Highly recommend for any one who has a blue tooth phone.\t', 

In [3]:

tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_inputs)
print(tokenizer.word_index)
tokenized_inputs = tokenizer.texts_to_sequences(train_inputs)
print(tokenized_inputs)


{'the': 1, 'i': 2, 'and': 3, 'it': 4, 'is': 5, 'a': 6, 'this': 7, 'to': 8, 'phone': 9, 'my': 10, 'for': 11, 'great': 12, 'not': 13, 'of': 14, 'very': 15, 'with': 16, 'in': 17, 'on': 18, 'was': 19, 'you': 20, 'that': 21, 'have': 22, 'good': 23, 'quality': 24, 'product': 25, 'battery': 26, 'works': 27, 'well': 28, 'had': 29, 'are': 30, 'sound': 31, 'but': 32, 'headset': 33, 'as': 34, 'all': 35, 'one': 36, "i've": 37, 'would': 38, 'no': 39, 'if': 40, 'use': 41, 'like': 42, 'so': 43, 'than': 44, 'ear': 45, 'recommend': 46, 'has': 47, 'price': 48, 'work': 49, "don't": 50, 'case': 51, 'up': 52, 'or': 53, 'service': 54, 'excellent': 55, 'be': 56, 'your': 57, 'time': 58, 'from': 59, 'at': 60, 'new': 61, "it's": 62, 'really': 63, 'more': 64, 'nice': 65, 'after': 66, 'only': 67, 'love': 68, '2': 69, 'worked': 70, 'also': 71, 'am': 72, 'me': 73, 'charger': 74, 'any': 75, 'do': 76, "i'm": 77, 'did': 78, 'ever': 79, 'money': 80, 'comfortable': 81, 'buy': 82, 'does': 83, 'too': 84, 'item': 85, 'bett

In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_inputs = pad_sequences(tokenized_inputs, padding='post')
train_labels = tf.convert_to_tensor(train_labels)
print(padded_inputs)


[[ 43 157   5 ...   0   0   0]
 [ 23  51  55 ...   0   0   0]
 [ 12  11   1 ...   0   0   0]
 ...
 [  4 120 121 ...   0   0   0]
 [114 266 321 ...   0   0   0]
 [ 81 154  20 ...   0   0   0]]


In [5]:
X = padded_inputs
Y = train_labels
print(X.shape)
print(Y.shape)
print(Y)

(700, 30)
(700,)
tf.Tensor(
[0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1
 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1
 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0
 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1
 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1
 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1
 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 0 1 0
 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1
 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 0

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [7]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=128))
model.add(LSTM(units=64, return_sequences=True))
model.add(LSTM(units=64))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# input_dim specify the vocab count, output_dim the dense vector dim, input_length the number of words in the sentence

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.fit(X, Y, epochs = 100)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.5428 - loss: 0.6943
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.5085 - loss: 0.6941
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.6783 - loss: 0.6249
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - accuracy: 0.8799 - loss: 0.3711
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.9115 - loss: 0.2947
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9540 - loss: 0.1876
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.9303 - loss: 0.2228
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9853 - loss: 0.0754
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9912 - loss: 0.0441
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9961 - loss: 0.0212
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9947 - loss: 0.0198
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step

KeyboardInterrupt: 

In [9]:

def predict(model, tokenizer, input):
  tokenized_inputs = tokenizer.texts_to_sequences(input)
  padded_inputs = pad_sequences(tokenized_inputs, padding='post')
  predictions = model.predict(padded_inputs)
  return predictions

In [10]:
accuracy = 0
for i in range(len(test_inputs)):
    print(i, ':', test_inputs[i])
    prediction = predict(model, tokenizer, [test_inputs[i]])
    print(prediction)

    if prediction > 0.5:
        predicted_label = 1
        print("Positive")
    else:
        predicted_label = 0
        print("Negative")
    if( predicted_label == test_labels[i]):
        accuracy += 1
    print(predict(model, tokenizer, [test_inputs[i]]))
accuracy = accuracy/len(test_inputs)
print(f'accuracy = {accuracy}')

Also, the phone doesn't seem to accept anything except CBR mp3s, preferably ripped by Windows Media Player.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step
[[0.22858341]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.22858341]]
You can't beat the price on these.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step
[[0.46629876]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.46629876]]
* Comes with a strong light that you can use to light up your camera shots, and even flash SOS signals (seriously!	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[0.15294217]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.15294217]]
lightweight and works well.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.60494536]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.60494536]]
So just beware.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.48587382]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.48587382]]
I love this cable - it allows me to connect any mini-USB device to my PC.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0

In [12]:
text = 'I am pretty sure this is the right product for me'
print(predict(model, tokenizer, [text]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.7854562]]
