<a href="https://colab.research.google.com/github/Joshi-Atharva/Sentiment-analysis/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# Mounting the drive to use the files and images
import os
os.chdir('/content/drive/MyDrive/Sentiment analysis/')
print(os.listdir())
from extract import extract

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['Sentiment analysis.ipynb', 'train_set_sentiment.txt', 'extract.py', '__pycache__', 'train_set.txt', 'trainDataSet.txt']


In [2]:
file_path = 'train_set_sentiment.txt'
data = extract(file_path)
inputs = data.inputs
labels = data.labels
print(inputs)
print(labels)

['His achievement in the competition brought delight and a sense of pride to everyone.', 'She smiled brightly, feeling confident after her hard work resulted in success.', "The team's victory was remarkable, and they celebrated their harmony and strength.", 'Their friendship was filled with generosity and trust, creating a joyful bond.', 'We admired her amazing talent and sincere effort during the performance.', 'He cheerfully shared his excitement about the opportunity to explore new places.  ', 'She received a beautiful gift as a token of gratitude and respect.', 'The garden bloomed vibrantly, showcasing the beauty and wonder of nature.  ', 'The team worked creatively and achieved their goal with confidence and determination.  ', 'His hard work paid off, and he was proudly recognized for his excellence.  ', 'Their efforts in promoting peace and kindness were widely appreciated.  ', 'She tackled the challenge with positivity, skill, and courage, inspiring others.  ', 'We felt relaxed 

In [3]:

tokenizer = Tokenizer()
tokenizer.fit_on_texts(inputs)
print(tokenizer.word_index)
tokenized_inputs = tokenizer.texts_to_sequences(inputs)
print(tokenized_inputs)


{'the': 1, 'and': 2, 'a': 3, 'was': 4, 'his': 5, 'caused': 6, 'to': 7, 'of': 8, 'her': 9, 'their': 10, 'in': 11, 'with': 12, 'she': 13, 'he': 14, 'for': 15, 'everyone': 16, 'feeling': 17, 'filled': 18, 'by': 19, 'work': 20, 'led': 21, 'left': 22, 'brought': 23, 'sense': 24, 'respect': 25, 'team': 26, 'failure': 27, 'trust': 28, 'during': 29, 'shared': 30, 'project': 31, 'from': 32, 'among': 33, 'him': 34, 'stress': 35, 'fear': 36, 'loss': 37, 'hard': 38, "team's": 39, 'amazing': 40, 'opportunity': 41, 'as': 42, 'were': 43, 'appreciated': 44, 'earning': 45, 'attitude': 46, 'comfort': 47, 'leaving': 48, 'conflict': 49, 'behavior': 50, 'frustration': 51, 'words': 52, 'pain': 53, 'situation': 54, 'created': 55, 'remarks': 56, 'achievement': 57, 'after': 58, 'resulted': 59, 'success': 60, 'they': 61, 'celebrated': 62, 'harmony': 63, 'strength': 64, 'bond': 65, 'we': 66, 'performance': 67, 'about': 68, 'gratitude': 69, 'wonder': 70, 'nature': 71, 'efforts': 72, 'peace': 73, 'kindness': 74, '

In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_inputs = pad_sequences(tokenized_inputs, padding='post')
labels = tf.convert_to_tensor(labels)
print(padded_inputs)


[[  5  57  11 ... 138   7  16]
 [ 13 139 140 ...  60   0   0]
 [  1  39 142 ...  64   0   0]
 ...
 [  5 412  56 ...   0   0   0]
 [  1 129  54 ...   0   0   0]
 [  1 418 106 ...   0   0   0]]


In [5]:
X = padded_inputs
Y = labels
print(X.shape)
print(Y.shape)
print(Y)

(100, 14)
(100,)
tf.Tensor(
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(100,), dtype=int32)


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [9]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=128))
model.add(LSTM(units=64, return_sequences=True))
model.add(LSTM(units=64))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# input_dim specify the vocab count, output_dim the dense vector dim, input_length the number of words in the sentence

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.fit(X, Y, epochs = 100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - accuracy: 0.3973 - loss: 0.6924
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6010 - loss: 0.6708
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7370 - loss: 0.6331
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9069 - loss: 0.5368
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9785 - loss: 0.3691
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9807 - loss: 0.1767
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9753 - loss: 0.0912
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9753 - loss: 0.0686
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0138
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0077
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0051
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - lo

In [14]:
test_data = extract('trainDataSet.txt')
test_inputs = test_data.inputs
test_labels = test_data.labels
print(test_inputs)
print(test_labels)


def predict(model, tokenizer, input):
  tokenized_inputs = tokenizer.texts_to_sequences(input)
  padded_inputs = pad_sequences(tokenized_inputs, padding='post')
  predictions = model.predict(padded_inputs)
  return predictions

['Achievement requires consistent effort and perseverance.', 'She felt a sense of betrayal after the argument.', 'The view from the mountaintop was truly magnificent.', 'His abusive behavior caused distress to everyone.', 'They celebrated their success with a grand party.', 'The streets were filled with chaos after the storm.', 'Her genuine smile brightened everyone’s day.', 'His clumsy actions caused the vase to shatter.', 'The team admired her dedication to the project.', 'He angrily criticized the decision during the meeting.', 'The garden was vibrant and beautifully maintained.', 'She felt anxious before presenting her project.', 'Their friendship grew stronger over time.', 'The corrupt official was exposed in the scandal.', 'He explored the vibrant city streets with enthusiasm.', 'The food tasted disgusting and poorly prepared.', 'Her creativity shone in the beautifully designed artwork.', 'He neglected his responsibilities and faced consequences.', 'Their teamwork led to a succes

In [16]:
accuracy = 0
for i in range(len(test_inputs)):
    print(test_inputs[i])
    prediction = predict(model, tokenizer, [test_inputs[i]])
    print(prediction)

    if prediction > 0.5:
        predicted_label = 1
        print("Positive")
    else:
        predicted_label = 0
        print("Negative")
    if( predicted_label == test_labels[i]):
        accuracy += 1
    print(predict(model, tokenizer, [test_inputs[i]]))
accuracy = accuracy/len(test_inputs)
print(f'accuracy = {accuracy}')

Achievement requires consistent effort and perseverance.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.6886783]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.6886783]]
She felt a sense of betrayal after the argument.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.99352163]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.99352163]]
The view from the mountaintop was truly magnificent.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.323762]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.323762]]
His abusive behavior caused distress to everyone.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.01824583]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[0.01824583]]
They celebrated their success with a grand party.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[0.99180114]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.99180114]]
The streets were filled with chaos after the storm.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.3751403]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.3751403]]
Her gen

In [19]:
text = ''
print(predict(model, tokenizer, [text]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[0.5678679]]
